### PR TITLE
Partners

### PR DESCRIPTION
**Pull request by markjasongalang**
Hi, I've fixed the appearance of the logos (for responsiveness) based on the instructions of macky (our boss). The only remaining thing to do in this page is to add the actual data of the sponsors/partners. For now, I've added temporary images and links to it (try clicking the links to see if they work).

### CODE REVIEW

**Review by karumadesu — APPROVED** [review]
Good with this one, I think I'll just handle changes with the fonts, colors, etc. later

**Review by mackyclemen — APPROVED** [review]
LGTM as well. Would _possibly_ refactor JS code embedded to `partners.astro` to allow dynamic placement of elements. 👍

**Comment by markjasongalang** [comment]
@karumadesu  done changing the fonts, colors, background, etc..

**Comment by mackyclemen** [comment]
> @karumadesu | I'll just handle changes with the fonts, colors, etc. later
>> @markjasongalang | @karumadesu done changing the fonts, colors, background, etc..

yeah we'll be handling this, don't worry about it. HAHAHAHA

**Pull request merged**
