### PR TITLE
Capili projectlist

### PR DESCRIPTION
**Pull request by unhingeLemon**
Project List
Tape
Chain
Responsiveness
Bootstrap Font Size
A4 Image size
Visit Button onhover

### CODE REVIEW

**Review by karumadesu — CHANGES_REQUESTED** [review]
- Add a bit of space before the main page title
- Update fonts (Akira Expanded for title, DIN for content. Files are below as well)
- I think it would be better if the image itself was clickable rather than adding a button upon hover. I also think it would look better to display the title upon hover instead of a button. Check this link for reference (https://www.w3schools.com/howto/howto_css_image_overlay_title.asp)
- Also, add a little bit of space on the left and right side of the project images for small devices
(>= 576px). See photo for reference.

Akira Expanded and DIN Font - [fonts.zip](https://github.com/cs-expo-feu-tech/web-2023/files/10950262/fonts.zip)

image

**Comment by unhingeLemon** [comment]
added margin before the main page title, 
updated fonts, 
whole div clickable redirect - also display title/group name on hover, 
made the images smaller on >=576 to show margins
ref

**Review by karumadesu — CHANGES_REQUESTED** [review]
- Can you please recheck the fonts used? It should be similar to the first image below (Screenshot is from individual-projects page).
image
Though when I try viewing them on my device it looks like this instead: 
image

- Also, can you please check this one? There's still extra space on the bottom of the project card:
image

- Lastly, I think it would be nice if upon hover, you could apply a filter on the image that makes it darker to emphasize the title further.

**Once complied, I think it's ready for merging with the main branch. I'll ask Macky to have it checked one last time and then we're probably done with this page. Great job! <3**

**Comment by unhingeLemon** [comment]
preview
Here's the preview of my previous commit. Please let me know if there are other concerns. Thanks!

**Comment by mackyclemen** [comment]
> * Can you please recheck the fonts used? It should be similar to the first image below (Screenshot is from individual-projects page).

We really should create a global stylesheet for the common fonts in displays, headings, and regular text. I'll most probably self-assign this after we compile all the pages.

Review will follow in a while after changes have been applied. cc @unhingeLemon - _thanks, and great job!_

**Review by karumadesu — APPROVED** [review]

**Pull request merged**
